### ISSUE TITLE
Clicking "Sign up" with no email address shows the disposable email error

### ISSUE THREAD

**Issue by matteocontrini** [FriendsOfFlarum/disposable-emails#2] opened 2020-07-27 11:40 UTC
When clicking "Sign up" with no email address, an error saying that you can't use disposable emails is shown.

![immagine](https://user-images.githubusercontent.com/2164763/88537859-a08df980-d00e-11ea-8342-ba82b978b037.png)

I believe it sholuld instead leave the validation to Flarum core.

**Comment by SanketDube** [comment] 2021-05-19 11:11
Duplicate of #4

**Comment by imorland** [comment] 2021-05-22 18:59
Addressed in `v1.0.0`

**Closed as completed by imorland** 2021-05-22 18:59 UTC
